### ISSUE TITLE
Implementation of Boat.first_five using ActiveRecord.find fails rspec 

### ISSUE THREAD

**Issue by kjoewill** [learn-co-curriculum/model-class-methods-lab#43]
I implemented Boat.first_five as follows:

```Ruby
  def self.first_five
    self.first(5)
  end
```

this returns an Array instance correctly containing the first 5 boats but the rspec test case expects the boats returned in an Boat::ActiveRecord_Relation so that it can respond to #pluck.

Changing my implementation to the following passes the test:
```Ruby
  def self.first_five
    self.all.limit(5)
  end
```

What is confusing to me is that the instructions do not provide any guidance regarding implementation of this method and so it makes sense to choose my original implementation using the simpler Boat.first(n).

I believe that either more direction should be provided in the instructions or the test case should not assume return of an ActiveRecord_Relation.

**Comment by drakeltheryuujin** [comment]
Hi @kjoewill ,

It appears this issue is related to a number of existing issues with our specs found here: #39

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues. We'll take this information into consideration in upcoming releases of this curriculum.

Thanks for contributing! 💙
